namespace ServerApp.Models;

/// <summary>
/// Represents a product in the inventory system
/// </summary>
/// <remarks>
/// This class serves as the primary model for product data in the API,
/// containing all essential product information including category details
/// </remarks>
public class Product
{
    /// <summary>
    /// Unique identifier for the product
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Name of the product
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Price of the product in the system's currency
    /// </summary>
    public double Price { get; set; }

    /// <summary>
    /// Current stock level of the product
    /// </summary>
    public int Stock { get; set; }

    /// <summary>
    /// Category classification of the product
    /// </summary>
    public Category Category { get; set; } = new();
}

/// <summary>
/// Represents a product category in the inventory system
/// </summary>
/// <remarks>
/// Categories are used to organize products into logical groups
/// and facilitate product management and filtering
/// </remarks>
public class Category
{
    /// <summary>
    /// Unique identifier for the category
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Name of the category
    /// </summary>
    public string Name { get; set; } = string.Empty;
}

/// <summary>
/// Data transfer object for creating a new product
/// </summary>
/// <remarks>
/// This model is used specifically for POST requests to create new products.
/// It excludes the Id field as this will be generated by the system.
/// All other product information is required for creation.
/// </remarks>
public class CreateProductRequest
{
    /// <summary>
    /// Name of the new product
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Initial price of the new product
    /// </summary>
    public double Price { get; set; }

    /// <summary>
    /// Initial stock level of the new product
    /// </summary>
    public int Stock { get; set; }

    /// <summary>
    /// Category assignment for the new product
    /// </summary>
    public Category Category { get; set; } = new();
}

/// <summary>
/// Data transfer object for updating an existing product
/// </summary>
/// <remarks>
/// This model is used specifically for PUT requests to update existing products.
/// All fields must be provided even if only some are being updated,
/// ensuring consistent product state after updates.
/// </remarks>
public class UpdateProductRequest
{
    /// <summary>
    /// Updated name of the product
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Updated price of the product
    /// </summary>
    public double Price { get; set; }

    /// <summary>
    /// Updated stock level of the product
    /// </summary>
    public int Stock { get; set; }

    /// <summary>
    /// Updated category assignment for the product
    /// </summary>
    public Category Category { get; set; } = new();
}